---
gitea_urls:
  api: https://git.xsfx.dev/api/v1/

changelog:
  filters:
    exclude:
      - "^Bump version:"
      - ^\[NO CHANGELOG\]
      - "^build:"
      - "^ci:"
      - "^repo:"
      - "^test:"
      - "^docs:"

builds:
  - skip: true
